### ISSUE TITLE
Podświetlenie lub wyróżnienie dla [Solved]

### ISSUE THREAD

**Issue by ciastek1981** [linuxmintpl/mybb-plugin#11]
Fajnie wygląda jeżeli posty są wyraźnie oznaczone jako [Solved]

Przykład ze strony https://soportemybb.es/index.php

![solved](https://user-images.githubusercontent.com/45271112/49459603-b3c3d400-f7ef-11e8-9ec7-7a29577b9005.png)

[extras.min.zip](https://github.com/linuxmintpl/mybb-plugin/files/2645065/extras.min.zip)

Inny przykład ze strony https://webboard.pl/forum-134.html

![solved webboard](https://user-images.githubusercontent.com/45271112/49461228-7b25f980-f7f3-11e8-97b1-a0a6cea0a493.png)

[dvz.min.zip](https://github.com/linuxmintpl/mybb-plugin/files/2645150/dvz.min.zip)

**Comment by Ulvhedin** [comment]
Zrobione za pomocą prefixów dla wątków.
