### ISSUE TITLE
Lista ostatnich wiadomości.

### ISSUE THREAD

**Issue by dedito** [linuxmintpl/mybb-plugin#3]
Do rozeznania możliwość dodania do głównej strony forum listy ostatnich wiadomości.

**Comment by dedito** [comment]
Wygląda na to, że trzeba to zrobić pluginem.
Do rozeznania https://community.mybb.com/mods.php?action=view&pid=917

**Comment by dedito** [comment]
Kolejny plugin do rozeznania https://mods.mybb.com/view/recent-topics-on-index-page
https://community.mybb.com/mods.php?action=view&pid=191

**Comment by yahoob3** [comment]
OK, pociągnąłem wszystkie trzy. Popatrzę na localu.

**Comment by dedito** [comment]
Przetestowaliśmy kilka wtyczek (lista chyba pełna, jakby co to dajcie znać co jest do uzupełnienia)
[b]1. Last Post by vintagedaddyo[/b]
Strona domowa: https://community.mybb.com/mods.php?action=view&pid=917
Github:https://github.com/vintagedaddyo/MyBB_Plugin_Last_Posts
Uwagi: Nie pasował nam domyślny styl przewijania wątków. Pewnie rzecz do poprawienia, wtyczkę wyłączono.

[b]2. Latest Posts on sidebar by DanielM[/b]
Strona domowa: https://community.mybb.com/mods.php?action=view&pid=291
Github:
Uwagi: Był problem z czasem ostatniej odpowiedzi. Wszystkie wątki miały ten sam czas wynikający z ostatniej odpowiedzi na forum. Pewnie rzecz do poprawienia, ale nie drążyliśmy.

[b]3. ChangUonDyU - Advanced Statistics by vintagedaddyo[/b]
Strona domowa: https://community.mybb.com/mods.php?action=view&pid=1125
Github:
Uwagi: Bardzo fajna wtyczka z zaawansowanymi statystykami, ale gryzie się z Shoutboksem (nie można pisać).


Obecnie na forum testowym jest aktywna wtyczka [b]Recent Threads On Index by dragonexpert[/b]
Strona domowa: https://community.mybb.com/mods.php?action=view&pid=191
Github: https://github.com/dragonexpert/recentthreads

Wygląda na to co by pasowało wrzucić na produkcyjne forum.

**Comment by dedito** [comment]
Na forum trafiła wtyczka [b]Recent Threads On Index by dragonexpert[/b]
